### ISSUE TITLE
Add a TimerManager that would handle timers and resets them automatically if necessary

### ISSUE THREAD

**Issue by V-ed** [Vhoyon/Vramework#23]
Here's a quick and dirty implementation example to get you started :

```java
public final class TimerManager {
	
	private static HashMap<String, Thread> timers;
	
	private TimerManager(){}
	
	/**
	 * @param timerName Name of the timer
	 * @param delay Delay (in milliseconds) before doing the action
	 * @param action Action to do after the delay was finished, without being called again, which resets the delay
	 */
	public static void manage(final String timerName, final int delay, Runnable action){
		
		if(timers == null)
			timers = new HashMap<>();
		
		stopTimer(timerName);
		
		Thread timerThread = new Thread(() -> {
			
			try{
				
				Thread.currentThread().sleep(delay);
				
				action.run();
				
			}
			catch(InterruptedException e){}
			finally{
				timers.remove(timerName);
			}
			
		});
		
		timers.put(timerName, timerThread);
		
		timerThread.start();
		
	}
	
	public static void stopTimer(String timerName){
		
		if(timers.containsKey(timerName))
			timers.get(timerName).interrupt();
		
	}
	
}
```

**Comment by V-ed** [comment]
Instead of storing Threads in the timers hashmap, we might instead want to use the `java.util.Timer` utility of Java itself, so we are not completely reinventing the wheel here (and have the possibility of extending TimerManager much more easily).

**Comment by StephanoMehawej** [comment]
If we use Timers instead of Threads, I don't think we need a hashmap

**Comment by StephanoMehawej** [comment]
I would like to know why you have a stop timer in the manage method

**Comment by V-ed** [comment]
@StephanoMehawej

In the PR https://github.com/Vhoyon/Discord-Bot/pull/193, you modified the file MusicPlayer to interrupt the thread so your timer action is not actually done (if the user plays a track, it should stop the timer and not disconnect the bot).

This is exactly the reason why I added this method, to be able to stop a timer if so desired because something happened.

In that linked PR, you would need to tweak MusicPlayer to then call the TimerManager.stopTimer() method.

**Comment by StephanoMehawej** [comment]
What I meant is that we should not have a stopTimer call in the manager. Not sure tho

**Comment by V-ed** [comment]
@StephanoMehawej Oh, indeed, I misread, but we indeed need it because it's basically a way to reset the timer if the method is called on a timer that already exists.

Look at the PR that I linked in my previous comment, you'll see that it's exactly the same deal - if the timer exists, stop it. and start anew.
